jedis:
  host: localhost
  password:
  port: 6379
  timeout: 2000
  maxTotal: 15 # 最大连接数
  maxIdle: 10 # 最大空闲连接
  minIdle: 5 # 最小空闲连接
  maxWaitMillis: 10000 # 获取连接最大等待时间
  testOnBorrow: true # 获取连接时检测是否可用